# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "3.6"
# python 2.7 and pypy seem to have os issues with travis containers

services:
  - rabbitmq

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - py.test -v --cov nameko_cachetools --cov-report term-missing

after_success:
- codecov
